name: Generate List

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *" # run daily at 02:00 UTC

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Update pdses list
        run: |
          curl "https://raw.githubusercontent.com/mary-ext/atproto-scraping/refs/heads/trunk/state.json" -o data.json

      - name: Generate list
        run: pnpm run gen

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
