name: Build & deploy website

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # run daily at 03:00 UTC

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Generate site
        run: pnpm run site

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    concurrency:
      group: github-pages
      cancel-in-progress: true

    permissions:
      id-token: write
      pages: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
